### ISSUE TITLE
Error when trying to view a view counter in django admin

### ISSUE THREAD

**Issue by heilkitty** [svetlyak40wt/django-counter#2]
TypeError: format requires a mapping

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/django/core/handlers/base.py", line 92, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/django/contrib/admin/sites.py", line 490, in root
    return self.model_page(request, _url.split('/', 2))
  File "/usr/local/lib/python2.6/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, *_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/django/contrib/admin/sites.py", line 509, in model_page
    return admin_obj(request, rest_of_url)
  File "/usr/local/lib/python2.6/dist-packages/django/contrib/admin/options.py", line 1098, in **call**
    return self.change_view(request, unquote(url))
  File "/usr/local/lib/python2.6/dist-packages/django/db/transaction.py", line 240, in _commit_on_success
    res = func(_args, *_kw)
  File "/usr/local/lib/python2.6/dist-packages/django/contrib/admin/options.py", line 873, in change_view
    return self.render_change_form(request, context, change=True, obj=obj)
  File "/usr/local/lib/python2.6/dist-packages/django/contrib/admin/options.py", line 590, in render_change_form
    ], context, context_instance=context_instance)
  File "/usr/local/lib/python2.6/dist-packages/django/shortcuts/__init__.py", line 20, in render_to_response
    return HttpResponse(loader.render_to_string(_args, *_kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/django/template/loader.py", line 108, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 178, in render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 779, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 792, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/loader_tags.py", line 97, in render
    return compiled_parent.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 178, in render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 779, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 792, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/loader_tags.py", line 97, in render
    return compiled_parent.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 178, in render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 779, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 792, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/defaulttags.py", line 243, in render
    return self.nodelist_true.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 779, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 792, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/loader_tags.py", line 24, in render
    result = self.nodelist.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 779, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 792, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/defaulttags.py", line 243, in render
    return self.nodelist_true.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 779, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 792, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/defaulttags.py", line 244, in render
    return self.nodelist_false.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 779, in render
    bits.append(self.render_node(node, context))
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 792, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 826, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python2.6/dist-packages/django/template/**init**.py", line 572, in resolve
    new_obj = func(obj, *arg_vals)
  File "/usr/local/lib/python2.6/dist-packages/django/template/defaultfilters.py", line 37, in _dec
    args[0] = force_unicode(args[0])
  File "/usr/local/lib/python2.6/dist-packages/django/utils/encoding.py", line 71, in force_unicode
    s = unicode(s)
  File "/home/public_html/up-yachka.org.ua/communitydraft/community/apps/django_counter/models.py", line 52, in __unicode__
    return _('Counter for %(object)s = %(count)d') % (self.object, self.count)
  File "/usr/local/lib/python2.6/dist-packages/django/utils/functional.py", line 222, in __mod__
    return unicode(self) % rhs
TypeError: format requires a mapping

Fix:
In models.py change ViewCounter.**unicode** method from

return _('Counter for %(object)s = %(count)d') % (self.object, self.count)

to

return _('Counter for %s = %d') % (self.object, self.count)

**Comment by heilkitty** [comment]
Sorry for double-post, traceback is too big.

Fix:
In models.py change ViewCounter.**unicode** method from

return _('Counter for %(object)s = %(count)d') % (self.object, self.count)

to

return _('Counter for %s = %d') % (self.object, self.count)

**Comment by svetlyak40wt** [comment]
Fixed in version 0.1.5
